name: Angular Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: code/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: code
      - name: Run tests
        run: npm run test
        working-directory: code
      - name: Build
        run: npm run build
        working-directory: code
